name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
Â  push:
Â Â Â  branches: ['master']
Â  workflow_dispatch:Â jobs:
Â  buildImage:
Â Â Â  runs-on: ubuntu-latest
Â Â Â  steps:
Â Â Â Â Â  - name: Check out repository code
Â Â Â Â Â Â Â  uses: actions/checkout@v3
Â Â Â Â Â  - name: Set up Docker Buildx
Â Â Â Â Â Â Â  uses: docker/setup-buildx-action@v2
Â Â Â Â Â  - name: Azure Container Registry Login
Â Â Â Â Â Â Â  uses: Azure/docker-login@v1
Â Â Â Â Â Â Â  with:
Â Â Â Â Â Â Â Â Â  # Container registry username
Â Â Â Â Â Â Â Â Â  username: 'ccconreg'Â 
Â Â Â Â Â Â Â Â Â  # Container registry password
Â Â Â Â Â Â Â Â Â  password: 'dRCHShz45snIg3FA+QI64Nm1zZseE6myR66Gmhm/lC+ACRCqHv13'
Â Â Â Â Â Â Â Â Â  # Container registry server url
Â Â Â Â Â Â Â Â Â  login-server: 'ccconreg.azurecr.io'
Â Â Â Â Â  - name: Build and push
Â Â Â Â Â Â Â  uses: docker/build-push-action@v4
Â Â Â Â Â Â Â  with:
Â Â Â Â Â Â Â Â Â  push: true
Â Â Â Â Â Â Â Â Â  tags: ccdemo/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
Â  deployToAKS:
Â Â Â  runs-on: ubuntu-latest
Â Â Â  steps:
Â Â Â Â Â  - run: echo "hello"
